---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: salt_solo
  formula: zulip
  state_top:
    base:
      "*":
        - zulip

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        zulip.sls: pillar_custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - zulip
