---
driver:
  name: docker

provisioner:
  name: salt_solo
  formula: zulip
  state_top:
    base:
      "*":
        - zulip

platforms:
  - name: ubuntu-xenial
  - name: ubuntu-trusty

suites:
  - name: default
  
  - name: custom
    provisioner:
      pillars-from-files:
        zulip.sls: pillar_custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - zulip
